# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VWxn_RyHNW_dhfzuD72xtovFzJJQMnfU
"""

!pip install streamlit pandas

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import ephem
# import urllib.request
# from datetime import datetime, timedelta
# 
# # 페이지 기본 설정
# st.set_page_config(page_title="평택 밤하늘 대시보드", page_icon="🌌", layout="wide")
# 
# # 88개 별자리 한국어 매핑 데이터
# CONSTELLATION_KOREAN = {
#     'And': '안드로메다', 'Ant': '공기펌프', 'Aps': '극락조', 'Aqr': '물병', 'Aql': '독수리',
#     'Ara': '제단', 'Ari': '양', 'Aur': '마차부', 'Boo': '목동', 'Cae': '조각칼',
#     'Cam': '기린', 'Cnc': '게', 'CVn': '사냥개', 'CMa': '큰개', 'CMi': '작은개',
#     'Cap': '염소', 'Car': '용골', 'Cas': '카시오페아', 'Cen': '센타우루스', 'Cep': '세페우스',
#     'Cet': '고래', 'Cha': '카멜레온', 'Cir': '컴퍼스', 'Col': '비둘기', 'Com': '머리카락',
#     'CrA': '남쪽왕관', 'CrB': '북쪽왕관', 'Crv': '까마귀', 'Crt': '컵', 'Cru': '남십자',
#     'Cyg': '백조', 'Del': '돌고래', 'Dor': '황새치', 'Dra': '용', 'Equ': '조마',
#     'Eri': '에리다누스', 'For': '화로', 'Gem': '쌍둥이', 'Gru': '두루미', 'Her': '헤라클레스',
#     'Hor': '시계', 'Hya': '바다뱀', 'Hyi': '물뱀', 'Ind': '인디언', 'Lac': '도마뱀',
#     'Leo': '사자', 'LMi': '작은사자', 'Lep': '토끼', 'Lib': '천칭', 'Lup': '이리',
#     'Lyn': '살꽹이', 'Lyr': '거문고', 'Men': '테이블산', 'Mic': '현미경', 'Mon': '외뿔소',
#     'Mus': '파리', 'Nor': '직각자', 'Oct': '팔분의', 'Oph': '뱀주인', 'Ori': '오리온',
#     'Pav': '공작', 'Peg': '페가수스', 'Per': '페르세우스', 'Phe': '불새', 'Pic': '화가',
#     'Psc': '물고기', 'PsA': '남쪽물고기', 'Pup': '고물', 'Pyx': '나침반', 'Ret': '그물',
#     'Sge': '화살', 'Sgr': '궁수', 'Sco': '전갈', 'Scl': '조각가', 'Sct': '방패',
#     'Ser': '뱀', 'Sex': '육분의', 'Tau': '황소', 'Tel': '망원경', 'Tri': '삼각형',
#     'TrA': '남쪽삼각형', 'Tuc': '큰부리새', 'UMa': '큰곰', 'UMi': '작은곰', 'Vel': '돛',
#     'Vir': '처녀', 'Vol': '날치', 'Vul': '여우'
# }
# 
# def get_korean_constellation(body):
#     try:
#         abbr, _ = ephem.constellation(body)
#         return f"{CONSTELLATION_KOREAN.get(abbr, '알 수 없는')}자리"
#     except:
#         return "관측 불가"
# 
# def get_bearing(azimuth_rad):
#     az_deg = float(azimuth_rad) * 57.2958
#     bearings = ["북", "북북동", "북동", "동북동", "동", "동남동", "남동", "남남동",
#                 "남", "남남서", "남서", "서남서", "서", "서북서", "북서", "북북서"]
#     index = int((az_deg + 11.25) / 22.5) % 16
#     return f"{bearings[index]} ({az_deg:.1f}°)"
# 
# def get_moon_phase_korean(observer):
#     moon = ephem.Moon()
#     moon.compute(observer)
#     curr_p = moon.moon_phase
# 
#     orig_date = observer.date
#     observer.date = ephem.Date(observer.date + ephem.hour)
#     moon.compute(observer)
#     next_p = moon.moon_phase
#     observer.date = orig_date
# 
#     is_waxing = next_p > curr_p
#     if curr_p <= 0.02: return "삭 (새달)"
#     if curr_p >= 0.98: return "보름달 (망)"
#     if is_waxing:
#         if curr_p < 0.4: return "초승달"
#         if curr_p < 0.6: return "상현달"
#         return "차오르는 상현달"
#     else:
#         if curr_p > 0.6: return "기울어가는 하현달"
#         if curr_p > 0.4: return "하현달"
#         return "그믐달"
# 
# @st.cache_data(ttl=600)
# def fetch_satellite_tle():
#     urls = [
#         "https://celestrak.org/NORAD/elements/gp.php?GROUP=stations&FORMAT=tle",
#         "https://celestrak.org/NORAD/elements/gp.php?GROUP=visual&FORMAT=tle"
#     ]
#     sats = []
#     for url in urls:
#         try:
#             req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
#             with urllib.request.urlopen(req) as res:
#                 lines = res.read().decode('utf-8').splitlines()
#                 for i in range(0, len(lines)-2, 3):
#                     name = lines[i].strip()
#                     if "STARLINK" not in name.upper():
#                         sats.append((name, lines[i+1].strip(), lines[i+2].strip()))
#         except: continue
#     return sats
# 
# def main():
#     obs = ephem.Observer()
#     obs.lat, obs.lon, obs.elevation = '36.9921', '127.0802', 25
# 
#     now_utc = datetime.utcnow()
#     now_kst = now_utc + timedelta(hours=9)
#     obs.date = now_utc.strftime('%Y/%m/%d %H:%M:%S')
# 
#     st.title("🌌 평택 실시간 밤하늘 & 위성 관측 대시보드")
#     st.markdown(f"**📍 위치:** 경기도 평택시 | **⏰ 현재 시간:** {now_kst.strftime('%Y-%m-%d %H:%M:%S')} (KST)")
#     st.divider()
# 
#     col1, col2 = st.columns(2)
# 
#     with col1:
#         st.subheader("🌙 달(Moon) 상태")
#         moon = ephem.Moon()
#         moon.compute(obs)
#         m_alt = float(moon.alt) * 57.2958
#         if m_alt > 0:
#             st.info(f"**모양:** {get_moon_phase_korean(obs)} (약 {moon.moon_phase*100:.1f}% 조도)\n\n"
#                     f"**위치:** {get_bearing(moon.az)} 방향 | **고도:** {m_alt:.1f}° | **별자리:** {get_korean_constellation(moon)}")
#         else:
#             st.warning(f"현재 지평선 아래에 있습니다. (오늘의 달 모양: {get_moon_phase_korean(obs)})")
# 
#         st.subheader("🪐 현재 보이는 행성")
#         planets = {"수성": ephem.Mercury(), "금성": ephem.Venus(), "화성": ephem.Mars(), "목성": ephem.Jupiter(), "토성": ephem.Saturn()}
#         v_planets = 0
#         for name, p in planets.items():
#             p.compute(obs)
#             alt = float(p.alt) * 57.2958
#             if alt > 0:
#                 st.write(f"- ✨ **{name}** | {get_bearing(p.az)} | 고도: {alt:.1f}° | {get_korean_constellation(p)}")
#                 v_planets += 1
#         if v_planets == 0:
#             st.write("현재 지평선 위에 떠 있는 행성이 없습니다.")
# 
#     with col2:
#         st.subheader("🌌 머리 위 주요 길잡이 별")
#         stars = ['Polaris', 'Vega', 'Altair', 'Deneb', 'Arcturus', 'Spica', 'Antares']
#         star_data = []
#         for s_name in stars:
#             try:
#                 s = ephem.star(s_name)
#                 s.compute(obs)
#                 alt = float(s.alt) * 57.2958
#                 if alt > 0:
#                     star_data.append((alt, s_name, get_korean_constellation(s), get_bearing(s.az)))
#             except: continue
# 
#         if star_data:
#             star_data.sort(key=lambda x: x[0], reverse=True)
#             for alt, name, const, brg in star_data[:5]:
#                 st.write(f"- ⭐ **{name}** ({const}) | {brg} | 고도: {alt:.1f}°")
#         else:
#             st.write("관측 가능한 주요 길잡이 별이 없습니다.")
# 
#     st.divider()
# 
#     st.subheader("🛰️ 평택 상공 통과 중인 인공위성 및 우주정거장")
#     sat_list = fetch_satellite_tle()
#     v_sats = 0
#     for name, l1, l2 in sat_list:
#         try:
#             sat = ephem.readtle(name, l1, l2)
#             sat.compute(obs)
#             alt = float(sat.alt) * 57.2958
#             if alt > 0:
#                 kind = "🛸 우주정거장" if "ISS" in name or "TIANGONG" in name.upper() else "🛰️ 인공위성"
#                 st.write(f"- {kind} **{name}** | {get_bearing(sat.az)} | 고도: {alt:.1f}° | 거리: {sat.range/1000:.0f} km")
#                 v_sats += 1
#         except: continue
# 
#     if v_sats == 0:
#         st.info("현재 머리 위를 지나가는 주요 인공위성이 없습니다.")
# 
# if __name__ == "__main__":
#     main()

!npm install -g localtunnel

!streamlit run app.py & npx localtunnel --port 8501

!streamlit run app.py & ssh -o StrictHostKeyChecking=no -R 80:localhost:8501 serveo.net
